### ISSUE TITLE
Hey Dulanic, here is my warning. All your Photos/Videos are public!

### ISSUE THREAD

**Issue by mavinV6** [Dulanic/docker-compose#1]
https://github.com/Dulanic/docker-compose/blob/bfa08f0cc4d03e29175ddaa3132c24c15807ac61/docker-compose.yml#L332

https://bytemeta.vip/repo/photoprism/photoprism/issues/2222?page=2
PHOTOPRISM_SITE_URL="https://photos.dulanic.com"  # Public PhotoPrism URL

Everybody can look your photos and videos!!!

**Comment by Dulanic** [comment]
Thank you! I dont know how i missed that. I have CF zerotrust to proect all of them, but I somehow missed this one! All Fixed, thank you!
